//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAmazeUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FileInfo
    {
        public string Id { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public string FileSName { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public string AddUser { get; set; }
        public string UpType { get; set; }
        public Nullable<int> FileSize { get; set; }
    }
}
