//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAmazeUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_notice
    {
        public string Id { get; set; }
        public string NoticeNO { get; set; }
        public Nullable<System.DateTime> NDate { get; set; }
        public Nullable<int> NAddress { get; set; }
        public string ContactAccount { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<System.DateTime> UdateTime { get; set; }
        public string NTheme { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
        public bool IsUsed { get; set; }
        public string DelAccount { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string DelRemark { get; set; }
    }
}
