//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAmazeUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_project
    {
        public string Id { get; set; }
        public string CompName { get; set; }
        public string ProPhaseId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string ProManager { get; set; }
        public string ProWebUrl { get; set; }
        public string ProApp { get; set; }
        public string ProWeChat { get; set; }
        public string Originator { get; set; }
        public string OriginatorEmail { get; set; }
        public string OriginatorPhone { get; set; }
        public string Contact { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ProBrief { get; set; }
        public string InvestmentLogic { get; set; }
        public string InvestmentAmount { get; set; }
        public Nullable<System.DateTime> InvestmentTime { get; set; }
        public string ValueOfAssessment { get; set; }
        public Nullable<System.DateTime> ValueofTime { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
        public string ProName { get; set; }
        public string FinancingScale { get; set; }
        public bool IsUsed { get; set; }
        public string DelAccount { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string DelRemark { get; set; }
    }
}
