//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAmazeUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Account { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Utype { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string AccountIcon { get; set; }
    }
}
